import Head from "next/head";
import styles from "../styles/Home.module.css";

import "bootstrap/dist/css/bootstrap.css";

export async function getStaticProps() {
  const res = await fetch(
    "https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json"
  );
  const pokemon = await res.json();

  return {
    props: {
      pokemon,
    },
  };
}

// Function to generate a random color
const getRandomColor = () => {
  const letters = "0123456789ABCDEF";
  let color = "#";
  for (let i = 0; i < 6; i++) {
    color += letters[Math.floor(Math.random() * 16)];
  }
  return color;
};

export default function Home({ pokemon }) {
  return (
    <div className="container">
      <Head>
        <title>Pokemon List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Pokemon GO!</h1>

        <div className="row">
          {pokemon.map((poke) => (
            <div className="col-md-3 mt-5">
              <div
                className="card custom-card"
                style={{
                  boxShadow: `5px 5px ${getRandomColor()}`,
                  borderColor: ` ${getRandomColor()}`,
                }}
                key={poke.id}
              >
                <div className="circle-shadow"></div>
                <img
                  className="card-img-top custom-img mt-5 mb-5"
                  src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${poke.image}`}
                  alt={poke.name}
                />

                <div className="card-body">
                  <h5 className="card-title">{poke.name}</h5>
                  <a href={`/pokemon/${poke.id}`} className="btn btn-success">
                    See Detail
                  </a>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* <div className={styles.grid}>
          {pokemon.map((poke) => (
            <Link
              href={`/pokemon/${poke.id}`}
              className={styles.card}
              key={poke.id}
            >
              <h2>{poke.name}</h2>
            </Link>
          ))}
        </div> */}
      </main>
    </div>
  );
}
