import Link from "next/link";
import { IoChevronBackOutline } from "react-icons/io5";
import Head from "next/head";

// Generates `/posts/1` and `/posts/2`
export async function getStaticPaths() {
  const resp = await fetch(
    "https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json"
  );
  const pokemon = await resp.json();

  return {
    paths: pokemon.map((pokemon) => ({
      params: { id: pokemon.id.toString() },
    })),
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  const resp = await fetch(
    `https://jherr-pokemon.s3.us-west-1.amazonaws.com/pokemon/${params.id}.json`
  );

  return {
    props: {
      pokemon: await resp.json(),
    },
    // revalidate: 30,
  };
}

// Function to generate a random color
const getRandomColor = () => {
  const letters = "0123456789ABCDEF";
  let color = "#";
  for (let i = 0; i < 6; i++) {
    color += letters[Math.floor(Math.random() * 16)];
  }
  return color;
};

export default function pokemonDetail({ pokemon }) {
  return (
    <div className="container">
      <Head>
        <title>{pokemon.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <div className="d-flex justify-content-center">
        <div className="col-md-12">
          <div
            className="card"
            style={{
              boxShadow: `0 5px ${getRandomColor()}`,
              borderColor: ` ${getRandomColor()}`,
              borderRadius: "30px",
            }}
          >
            <div className="card-body m-3">
              <div className="d-flex justify-content-start aligns-item-center">
                <Link href={"/"}>
                  <div
                    className="circle-back"
                    style={{
                      backgroundColor: ` ${getRandomColor()}`,
                    }}
                  >
                    <IoChevronBackOutline className="icon-back" />
                  </div>
                </Link>

                <h2 className="pokemon-name ms-3">{pokemon.name}</h2>
              </div>

              <div className="row mt-2">
                <div className="col-md-3">
                  <img
                    className="img-fluid "
                    src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${pokemon.image}`}
                    alt={pokemon.name.english}
                  />
                </div>
                <div className="col-md-6 ms-3 ">
                  <div className="d-flex justify-content-start ">
                    {pokemon.type.map((types) => (
                      <h3>
                        <span
                          className="badge rounded-pill ms-2"
                          key={types}
                          style={{
                            boxShadow: `0 3px ${getRandomColor()}`,
                            background: ` ${getRandomColor()}`,
                          }}
                        >
                          {types}
                        </span>
                      </h3>
                    ))}
                  </div>

                  <div className="mt-4">
                    {pokemon.stats.map(({ name, value }) => (
                      <div className="mt-3" key={name}>
                        <div className="progress">
                          <div
                            className="progress-bar progress-bar-striped progress-bar-animated"
                            aria-valuemax="100"
                            style={{
                              width: `${value}%`,
                              background: ` ${getRandomColor()}`,
                              borderRadius: "5px",
                            }}
                          >
                            {name} ({value})
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="col-md-3"></div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* <div className={styles.section}>
        <Link href={"/"}>Back to list</Link>
        <img
          className={styles.picture}
          src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${pokemon.image}`}
          alt={pokemon.name.english}
        />
        <div className={styles.section2}>
          <h1>{pokemon.name}</h1>
          <p>{pokemon.type.join(", ")}</p>
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Value</th>
              </tr>
            </thead>
            <tbody>
              {pokemon.stats.map(({ name, value }) => (
                <tr key={name}>
                  <td>{name}</td>
                  <td>{value}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div> */}
    </div>
  );
}
